local json = require("riftapi.json")
describe("Test json module", function()
    describe("Test _json_str", function()
        it("returns 'null' for nil", function()
            assert.equal(json._json_str(nil), "null")
        end)
        it("returns encoded string for str", function()
            assert.equal(json._json_str("foo"), '"foo"')
        end)
    end)
    describe("Test _json_opt_int", function()
        it("returns 'null' for nil", function()
            assert.equal(json._json_opt_int(nil), "null")
        end)
        it("returns int for int", function()
            assert.equal(json._json_opt_int(1), 1)
        end)
    end)
    describe("Test _json_opt_bool", function()
        it("returns 'null' for nil", function()
            assert.equal(json._json_opt_bool(nil), "null")
        end)
        it("returns true/false for true/false", function()
            assert.equal(json._json_opt_bool(true), "true")
            assert.equal(json._json_opt_bool(false), "false")
        end)
    end)
    describe("Test _json_arr", function()
        it("returns '[]' for nil", function()
            assert.equal(json._json_arr(nil), "[]")
        end)
        it("returns array of strings for string[]", function()
            assert.equal(json._json_arr({ "a", "b" }), '["a","b"]')
        end)
    end)
    describe("Test encode/decode", function()
        it("encodes nested tables", function()
            assert.equal(json.encode({ a = "b", c = { d = { "e", "f" } } }), [[{"a":"b","c":{"d":["e","f"]}}]])
        end)
        it("decodes nested tables", function()
            assert.same(json.decode([[{"a":"b","c":{"d":["e","f"]}}]]), { a = "b", c = { d = { "e", "f" } } })
        end)
    end)
end)
