local rift = require("riftapi")
---busted
describe("Test query commands #query #needsrift", function()
    local client_ok = rift.get_client()
    if not client_ok then
        ---@diagnostic disable-next-line: missing-parameter
        pending("rift server is not running, skipping dependent tests")
        return
    end

    describe("Test query.workspaces", function()
        it("executes successfully", function()
            local workspaces, err = rift.query.workspaces()
            assert.truthy(workspaces)
            assert.is_nil(err)
        end)
    end)
    describe("Test query.config", function()
        it("executes successfully", function()
            local config, err = rift.query.config()
            assert.truthy(config)
            assert.is_nil(err)
        end)
    end)
    describe("Test query.metrics", function()
        it("executes successfully", function()
            local metrics, err = rift.query.metrics()
            assert.truthy(metrics)
            assert.is_nil(err)
        end)
    end)
    describe("Test query.displays", function()
        it("executes successfully", function()
            local displays, err = rift.query.displays()
            assert.truthy(displays)
            assert.is_nil(err)
        end)
    end)
    describe("Test query.applications", function()
        it("executes successfully", function()
            local applications, err = rift.query.applications()
            assert.truthy(applications)
            assert.is_nil(err)
        end)
    end)
    describe("Test query.windows", function()
        it("executes successfully", function()
            local windows, err = rift.query.windows()
            assert.truthy(windows)
            assert.is_nil(err)
        end)
    end)
    describe("Test query.window_info", function()
        it("executes successfully", function()
            ---@diagnostic disable-next-line: missing-parameter
            pending("tbd, requires us to get a valid window_id first")
            local windows, err = rift.query.window_info({ idx = 0, pid = 0 })
            assert.truthy(windows)
            assert.is_nil(err)
        end)
    end)
    describe("Test query.workspaces", function()
        it("executes successfully", function()
            local workspaces, err = rift.query.workspaces()
            assert.truthy(workspaces)
            assert.is_nil(err)
        end)
    end)
    describe("Test query.layout_state", function()
        it("executes successfully", function()
            -- WARN: will fail if not on macos native space 1 when executing
            -- assumption is most will be
            local state, err = rift.query.layout_state(1)
            assert.truthy(state)
            assert.is_nil(err)
        end)
    end)
    describe("Test query.workspace_layouts", function()
        it("executes successfully", function()
            local state, err = rift.query.workspace_layouts()
            assert.truthy(state)
            assert.is_nil(err)
        end)
    end)
end)
